module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,html}"],
  theme: {
    extend: {
      fontFamily: {
        matter: ["Matter", "sans-serif"],
        // roboto: ["Roboto", "san-serif"],
      },
      transform: ["group-hover"],
      animation: {
        float: "float 6s ease-in-out infinite",
        progress: "progress 3s ease-in-out infinite",
        gradientShift: "gradientShift 6s ease infinite",
        blob: "blob 7s infinite",
        progress: "progress 3s ease-in-out infinite",
        pingSlow: 'ping 4s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        progress: {
          "0%": { width: "0%" },
          "50%": { width: "80%" },
          "100%": { width: "100%" },
        },
        gradientShift: {
          // ✅ add keyframes
          "0%": {
            backgroundPosition: "0% 50%",
          },
          "50%": {
            backgroundPosition: "100% 50%",
          },
          "100%": {
            backgroundPosition: "0% 50%",
          },
        },
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        progress: {
          "0%, 100%": { width: "0%" },
          "50%": { width: "100%" },
        },
      },
      backgroundSize: {
        "200%": "200% 200%",
      },
      backgroundPosition: {
        "0-center": "0% 50%",
        "100-center": "100% 50%",
      },
    },
    safelist: [
      "bg-gradient-to-br",
      "bg-rose-100",
      "bg-yellow-100",
      "bg-blue-100",
      "bg-green-100",
      "bg-purple-100",
      "border-rose-200",
      "border-yellow-200",
      "border-blue-200",
      "border-green-200",
      "border-purple-200",
      "from-indigo-400",
      "via-purple-500",
      "to-purple-700",
      "from-pink-400",
      "via-pink-500",
      "to-red-500",
      "from-blue-400",
      "via-sky-400",
      "to-cyan-400",
      "from-green-400",
      "via-teal-300",
      "to-emerald-400",
      "from-rose-400",
      "via-pink-300",
      "to-yellow-300",
      "from-cyan-200",
      "via-pink-200",
      "to-pink-300",
      "bg-gradient-to-br",
      "from-[#ff9a9e]",
      "to-[#fecfef]",
      "from-[#a18cd1]",
      "to-[#fbc2eb]",
      "from-[#ffecd2]",
      "to-[#fcb69f]",
      "from-[#d4fc79]",
      "to-[#96e6a1]",
      "from-[#84fab0]",
      "to-[#8fd3f4]",
      "from-[#ffd3a5]",
      "to-[#fd9853]",
      "from-[#84fab0]",
      "to-[#8fd3f4]",
      "from-[#a18cd1]",
      "to-[#fbc2eb]",
      "from-[#ffecd2]",
      "to-[#fcb69f]",
      "from-[#d4fc79]",
      "to-[#96e6a1]",
      "from-[#ff9a9e]",
      "to-[#fecfef]",
      "from-[#a8e6cf]",
      "to-[#dcedc1]",
      "from-[#ffd3a5]",
      "to-[#fd9853]",
      "from-[#a8edea]",
      "to-[#fed6e3]",
      "from-[#d299c2]",
      "to-[#fef9d7]",
      "from-[#ff9a9e]",
      "to-[#fecfef]",
      "from-[#a18cd1]",
      "to-[#fbc2eb]",
      "from-[#ffecd2]",
      "to-[#fcb69f]",
      "from-[#d4fc79]",
      "to-[#96e6a1]",
      "from-[#84fab0]",
      "to-[#8fd3f4]",
    ],
      boxShadow: {
        'performance': `
          inset 0 12px 12px 0 rgb(255 255 255 / 32%),
          inset 0 1px 0 0 rgb(255 255 255 / 32%),
          0 0px 0 0 rgba(0, 31, 31, 0.08)
        `,
      },
  },
  plugins: [],
};
